FROM keymetrics/pm2:12-alpine

RUN apk update
RUN apk add nodejs
RUN apk add npm
RUN apk add git


ADD . /home/service/
WORKDIR /home/service/
COPY .env.prod .env

RUN npm install
RUN ls
CMD [ "pm2-runtime", "start", "app.js" ]